### ISSUE TITLE
Remove "www." before reference pages

### ISSUE THREAD

**Issue by TheAlexLichter** [Pingu501/homepage#1]
Hey!

I'd suggest that you remove the "www." part of the reference pages (and maybe also think about changing the capitalization). It looks clearer then IMO.

![screenshot from 2017-11-11 13-10-02](https://user-images.githubusercontent.com/640208/32689272-a971b57a-c6e1-11e7-91a2-4f1fac43b41b.png)

**Comment by Pingu501** [comment]
Thx for the feedback!

I think you are right, fixed it right now :)

3f95600724fa6c48556c50dbbd4df30f8bce1c3d
